In [1]:
import babypandas as bpd

from notebook.services.config import ConfigManager
cm = ConfigManager()
cm.update('livereveal', {
        'width': 1024,
        'height': 768,
        'scroll': True,
})

{'width': 1024, 'height': 768, 'scroll': True}

# Lecture 3: Arrays and Tables

# How do we store *sequences*?

For instance:
- all temperatures in month of January
- the age of every user on Facebook
- the salary of every NBA player

## Each as own variable?

In [2]:
temperature_on_jan_01 = 68
temperature_on_jan_02 = 72
temperature_on_jan_03 = 65
temperature_on_jan_04 = 64
temperature_on_jan_05 = 62
temperature_on_jan_06 = 61
temperature_on_jan_07 = 59
temperature_on_jan_08 = 64
temperature_on_jan_09 = 64
temperature_on_jan_10 = 63
temperature_on_jan_11 = 65
temperature_on_jan_12 = 62

```
avg_temperature = 1/12 * (
    temperature_on_jan_01
    + temperature_on_jan_02
    + temperature_on_jan_03
    + ...)
```

## Python's `list`s

- To create a `list`, place commas between things and surround with square brackets:

In [3]:
temperature_list = [68, 72, 65, 64, 62, 61, 59, 64, 64, 63, 65, 62]
temperature_list

[68, 72, 65, 64, 62, 61, 59, 64, 64, 63, 65, 62]

In [4]:
temperature_list = [temperature_on_jan_01, 72, 65, temperature_on_jan_04, 62, 61, 59, 64, 64, 63, 65, 62]
temperature_list

[68, 72, 65, 64, 62, 61, 59, 64, 64, 63, 65, 62]

## `list`s make working with sequences easy

In [5]:
# compute the average temperature using `sum`
sum(temperature_list) / len(temperature_list)

64.08333333333333

## The Problem

- Lists are sloowwww
- Not a big deal when there aren't many entries
- A big problem when there are millions/billions of entries

# Arrays
* Like lists, but faster.
* Slightly less easy to work with.
* Provided by a package called `numpy`

In [6]:
import numpy as np

## Creating arrays

- To create an array, pass a list to the `np.array` function
- Remember the square brackets!

In [7]:
temperature_array = np.array([68, 72, 65, 64, 62, 61, 59, 64, 64, 63, 65, 62])
temperature_array

array([68, 72, 65, 64, 62, 61, 59, 64, 64, 63, 65, 62])

In [8]:
np.array(temperature_list)

array([68, 72, 65, 64, 62, 61, 59, 64, 64, 63, 65, 62])

## Accessing elements of arrays

- The things inside of an array are called its *elements*
- To get a particular element, use `[]`:

In [9]:
temperature_array

array([68, 72, 65, 64, 62, 61, 59, 64, 64, 63, 65, 62])

In [10]:
temperature_array[3]

64

## Warning!

- Python (like most languages) starts counting from 0, not 1!

In [11]:
# get the first element of the array
temperature_array[0]

68

## Out-of-bounds errors

In [12]:
temperature_array[42]

IndexError: index 42 is out of bounds for axis 0 with size 12

## Array/Number arithmetic

- `numpy` arrays make it easy to do the same thing to every element

In [13]:
temperature_array

array([68, 72, 65, 64, 62, 61, 59, 64, 64, 63, 65, 62])

In [14]:
# increase all temperatures by 3 degrees
temperature_array + 3

array([71, 75, 68, 67, 65, 64, 62, 67, 67, 66, 68, 65])

In [15]:
# halve all temperatures
temperature_array / 2

array([34. , 36. , 32.5, 32. , 31. , 30.5, 29.5, 32. , 32. , 31.5, 32.5,
       31. ])

In [16]:
# convert all temperatures to Celsius
(5/9) * (temperature_array - 32)

array([20.        , 22.22222222, 18.33333333, 17.77777778, 16.66666667,
       16.11111111, 15.        , 17.77777778, 17.77777778, 17.22222222,
       18.33333333, 16.66666667])

## Array/Array arithmetic

- two arrays of the same size can be added, subtracted, multiplied, etc.
- the arithmetic happens *elementwise*

In [17]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [18]:
a1

array([1, 2, 3])

In [19]:
a2

array([4, 5, 6])

In [20]:
a1 + a2

array([5, 7, 9])

In [21]:
a1 - a2

array([-3, -3, -3])

In [22]:
a1 * a2

array([ 4, 10, 18])

## Arrays for basic statistics: newborn birth weight

In [23]:
#: four girls with weight in kg: g1 = 3.405, g2 = 3.207, g3 = 2.42, g4 = 3.984

g1 = 3.405 
g2 = 3.207
g3 = 2.42
g4 = 3.984

# average weight of a newborn girl (in kg): 3.3
girl_av_weight = 3.3

### Load the weights into an array of floats

In [24]:
weights_kg_g = np.array([g1, g2, g3, g4]) 

weights_kg_g

array([3.405, 3.207, 2.42 , 3.984])

### Calculate the deviation of weights from the average weight
* Subtracting a number from an array subtracts the number from each element.

In [25]:
weights_kg_g - girl_av_weight

array([ 0.105, -0.093, -0.88 ,  0.684])

### Convert the weights to pounds (2.2 kg/lb)

In [26]:
weights_lbs_g = weights_kg_g * 2.2
weights_lbs_g

array([7.491 , 7.0554, 5.324 , 8.7648])

### How many girls are recorded in the array?

- The function `len()` returns the length of an array (or list).

In [27]:
len(weights_lbs_g)

4

## Arrays for basic statistics: daily temperatures

### Below is an array of daily high temperatures in San Diego from August 2018

In [28]:
temps = np.array([86, 85, 85, 84, 85, 86, 91, 89, 90, 88, 88, 85, 83, 82, 79, 81, 82,
                   83, 82, 79, 81, 83, 83, 79, 80, 80, 79, 80, 82, 82, 80])

Numbers of days temperatures are collected in August:

In [29]:
len(temps)

31

### temperature statistics (mean, min, max)

- Arrays have handy methods for common tasks

In [30]:
temps.sum() / len(temps)  # SOLUTION

83.29032258064517

In [31]:
temps.mean() # build the mean method

83.29032258064517

In [32]:
max(temps) # builtin functions work on array

91

In [33]:
temps.max() # the array has it's own min/max method (faster)

91

# Ranges

- We often find ourselves needing to make arrays like this:

In [34]:
days_in_january = np.array([
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 
    13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 
    23, 24, 25, 26, 27, 28, 29, 30, 31
])

# Ranges
* A range is an array of consecutive numbers
* ```np.arange(end)```: An array of increasing integers from 0 up to (and excluding!) end
* ```np.arange(start, end)```: An array of increasing integers from start up to (excluding!) end
* ```np.arange(start, end, step)```: A range with step between consecutive values
* The range always includes start but excludes end (i.e. a half-open interval)

In [35]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [36]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [37]:
np.arange(3, 30, 5)

array([ 3,  8, 13, 18, 23, 28])

In [38]:
np.arange(-3, 2, 0.5)

array([-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5])

In [39]:
np.arange(1, -3)

array([], dtype=int64)

## Discussion Question

On the first day of January, you are paid 1 cent. Every day thereafter, your pay doubles: on the 2nd day it is 2 cents, on the 3rd it is 4 cents, on the 4th it is 8 cents, and so on.

January has 31 days.

Which of these expressions calculates the total amount of money you'll make in January (in dollars)?

- A) `(2**(np.arange(31) * .01)).sum()`
- B) `(2**(np.arange(32) * .01)).sum()`
- C) `((2**np.arange(31)) * .01).sum()`
- D) `((2**np.arange(32)) * .01).sum()`

_Type your answer here, replacing this text._

**Solution**: (C)

In [40]:
np.arange(31) # SOLUTION

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [41]:
2**np.arange(31) # SOLUTION

array([         1,          2,          4,          8,         16,
               32,         64,        128,        256,        512,
             1024,       2048,       4096,       8192,      16384,
            32768,      65536,     131072,     262144,     524288,
          1048576,    2097152,    4194304,    8388608,   16777216,
         33554432,   67108864,  134217728,  268435456,  536870912,
       1073741824])

In [42]:
2**np.arange(31) * .01 # SOLUTION

array([1.00000000e-02, 2.00000000e-02, 4.00000000e-02, 8.00000000e-02,
       1.60000000e-01, 3.20000000e-01, 6.40000000e-01, 1.28000000e+00,
       2.56000000e+00, 5.12000000e+00, 1.02400000e+01, 2.04800000e+01,
       4.09600000e+01, 8.19200000e+01, 1.63840000e+02, 3.27680000e+02,
       6.55360000e+02, 1.31072000e+03, 2.62144000e+03, 5.24288000e+03,
       1.04857600e+04, 2.09715200e+04, 4.19430400e+04, 8.38860800e+04,
       1.67772160e+05, 3.35544320e+05, 6.71088640e+05, 1.34217728e+06,
       2.68435456e+06, 5.36870912e+06, 1.07374182e+07])

## (Optional) Speed Comparison, list vs array

In [43]:
n = 1_000_000
lst = list(range(n))
arr = np.arange(n)

In [54]:
sum(lst)

499999500000

In [55]:
arr.sum()

499999500000

In [56]:
%%timeit
_ = sum(lst)

7.17 ms ± 150 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [57]:
%%timeit 
_ = arr.sum()

534 µs ± 14.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [100]:
# compute ratio
(534e-6) / (7.17e-3) # SOLUTION

0.07447698744769873

# Tables

<img width=75% src="./data/imdb.png"/>

## How do we store *tabular data*?

- Could have an array for title, another for rating, another for year, etc.
- But this is not convenient.
- Instead, we use something called a *DataFrame*

In [59]:
bpd.read_csv('data/imdb.csv')

Votes  Rating                                  Title  Year  Decade
0      88355     8.4                                      M  1931    1930
1     132823     8.3                    Singin' in the Rain  1952    1950
2      74178     8.3                          All About Eve  1950    1950
3     635139     8.6                                   Léon  1994    1990
4     145514     8.2                       The Elephant Man  1980    1980
..       ...     ...                                    ...   ...     ...
245  1078416     8.7                           Forrest Gump  1994    1990
246    31003     8.1                  Le salaire de la peur  1953    1950
247   167076     8.2                               3 Idiots  2009    2000
248    91689     8.1                                Network  1976    1970
249   589477     8.3  Eternal Sunshine of the Spotless Mind  2004    2000

[250 rows x 5 columns]

## `pandas`

- DataFrames are provided by a package called `pandas`
- `pandas` is *the* tool for doing data science in Python
    - downloaded $380,000$ times *yesterday*
    - last month: 14 million downloads

## But `pandas` is not so cute...

<img height=100% src="./data/angrypanda.jpg"/>

## Instead

- We at UCSD have created a smaller, nicer version of `pandas`
- Keeps important stuff, throws out the rest.
- Easier to learn, but is still valid `pandas` code.

## We call it `babypandas`

<img height=75% src="./data/babypanda.jpg"/>

## Importing `babypandas`

In [60]:
import babypandas as bpd

## Table Structure

- Tables have *columns* and *rows*
- Can think of each column as an array
- Every column has a label: "Votes", "Rating", etc.
- Every row does too: 0, 1, 2, 3

In [61]:
movies = bpd.read_csv('data/imdb.csv').take(np.arange(4))
movies

Votes  Rating                Title  Year  Decade
0   88355     8.4                    M  1931    1930
1  132823     8.3  Singin' in the Rain  1952    1950
2   74178     8.3        All About Eve  1950    1950
3  635139     8.6                 Léon  1994    1990

## The Index

- Together, the row labels are called the *index*.
- It's not a separate column!

In [62]:
movies

Votes  Rating                Title  Year  Decade
0   88355     8.4                    M  1931    1930
1  132823     8.3  Singin' in the Rain  1952    1950
2   74178     8.3        All About Eve  1950    1950
3  635139     8.6                 Léon  1994    1990

## Setting a new index

- Can set a better index using `.set_index(column_name)`
- Row labels should (ideally) be unique identifiers.
- Returns a copy!
- Looks nicer, but also really useful.

In [63]:
movies_by_name = movies.set_index('Title')
movies_by_name

Votes  Rating  Year  Decade
Title                                            
M                     88355     8.4  1931    1930
Singin' in the Rain  132823     8.3  1952    1950
All About Eve         74178     8.3  1950    1950
Léon                 635139     8.6  1994    1990

## The index is an array

In [64]:
movies_by_name

Votes  Rating  Year  Decade
Title                                            
M                     88355     8.4  1931    1930
Singin' in the Rain  132823     8.3  1952    1950
All About Eve         74178     8.3  1950    1950
Léon                 635139     8.6  1994    1990

In [65]:
movies_by_name.index

Index(['M', 'Singin' in the Rain', 'All About Eve', 'Léon'], dtype='object', name='Title')

## Discussion Question

Which of these will return `Léon`?

- A) `movies_by_name['Title'][3]`
- B) `movies_by_name['Title'][4]`
- C) `movies_by_name.index[3]`
- D) `movies_by_name.index[4]`

_Type your answer here, replacing this text._

**Solution**: (C)

In [101]:
movies_by_name.index[3] # SOLUTION

'Léon'

# NBA Salaries

- The file `nba_salaries.csv` contains all salaries from 2015-2016 NBA season.
- CSV: *Comma-separated values*

In [69]:
print(open('data/nba_salaries.csv').read())

PLAYER,POSITION,TEAM,2015_SALARY
Paul Millsap,PF,Atlanta Hawks,18.671659
Al Horford,C,Atlanta Hawks,12.0
Tiago Splitter,C,Atlanta Hawks,9.75625
Jeff Teague,PG,Atlanta Hawks,8.0
Kyle Korver,SG,Atlanta Hawks,5.746479
Thabo Sefolosha,SF,Atlanta Hawks,4.0
Mike Scott,PF,Atlanta Hawks,3.333333
Kent Bazemore,SF,Atlanta Hawks,2.0
Dennis Schroder,PG,Atlanta Hawks,1.7634
Tim Hardaway Jr.,SG,Atlanta Hawks,1.3045200000000001
Walter Tavares,C,Atlanta Hawks,1.0
Jason Richardson,SG,Atlanta Hawks,0.947276
Lamar Patterson,SG,Atlanta Hawks,0.525093
Terran Petteway,SG,Atlanta Hawks,0.525093
Avery Bradley,PG,Boston Celtics,7.730337
Isaiah Thomas,PG,Boston Celtics,6.912869000000001
Jae Crowder,SF,Boston Celtics,6.796117
Jonas Jerebko,PF,Boston Celtics,5.0
Marcus Smart,PG,Boston Celtics,3.4310400000000003
Evan Turner,SG,Boston Celtics,3.42551
Tyler Zeller,C,Boston Celtics,2.616975
Jared Sullinger,C,Boston Celtics,2.56926
Kelly Olynyk,C,Boston Celtics,2.1651599999999998
Perry Jones,SF,Boston Celtics,2.038206

## Reading a CSV

- We can read a CSV using `bpd.read_csv()`. Give it name of the file.

In [70]:
salaries = bpd.read_csv('data/nba_salaries.csv')
salaries

PLAYER POSITION                TEAM  2015_SALARY
0       Paul Millsap       PF       Atlanta Hawks    18.671659
1         Al Horford        C       Atlanta Hawks    12.000000
2     Tiago Splitter        C       Atlanta Hawks     9.756250
3        Jeff Teague       PG       Atlanta Hawks     8.000000
4        Kyle Korver       SG       Atlanta Hawks     5.746479
..               ...      ...                 ...          ...
412        Gary Neal       PG  Washington Wizards     2.139000
413     DeJuan Blair        C  Washington Wizards     2.000000
414  Kelly Oubre Jr.       SF  Washington Wizards     1.920240
415   Garrett Temple       SG  Washington Wizards     1.100602
416     Jarell Eddie       SG  Washington Wizards     0.561716

[417 rows x 4 columns]

## Discussion Question

What would be a good column to use as the index?

- A) PLAYER
- B) POSITION
- C) TEAM
- D) 2015_SALARY

Is there something we should be worried about?

_Type your answer here, replacing this text._

**Solution**: (A)

- We'll use the player name.
- But we should be careful that two players don't have the same name.

## Setting the index

In [71]:
salaries_by_player = salaries.set_index('PLAYER')
salaries_by_player

POSITION                TEAM  2015_SALARY
PLAYER                                                   
Paul Millsap          PF       Atlanta Hawks    18.671659
Al Horford             C       Atlanta Hawks    12.000000
Tiago Splitter         C       Atlanta Hawks     9.756250
Jeff Teague           PG       Atlanta Hawks     8.000000
Kyle Korver           SG       Atlanta Hawks     5.746479
...                  ...                 ...          ...
Gary Neal             PG  Washington Wizards     2.139000
DeJuan Blair           C  Washington Wizards     2.000000
Kelly Oubre Jr.       SF  Washington Wizards     1.920240
Garrett Temple        SG  Washington Wizards     1.100602
Jarell Eddie          SG  Washington Wizards     0.561716

[417 rows x 3 columns]

### Shape of a table:

- `.shape` returns the number of rows and number of columns
- Access each with `[]`:

In [72]:
salaries_by_player.shape

(417, 3)

In [73]:
salaries_by_player.shape[0]

417

In [74]:
salaries_by_player.shape[1]

3

## Use Case: Adjust for Inflation

- These salaries are old. We should adjust for inflation
- $\$1.00$ in 2015 = $\$1.09$ in 2020
- Workflow:
    - get the column of salaries
    - multiply every element by 1.09
    - add new column to table

### Step 1) Getting a column

- We can get a column from a dataframe using `.get(column_name)`:
- Warning: case sensitive!
- The result looks like a 1-column DataFrame, but is actually a *Series*

In [75]:
salaries_by_player.get("2015_SALARY")

PLAYER
Paul Millsap       18.671659
Al Horford         12.000000
Tiago Splitter      9.756250
Jeff Teague         8.000000
Kyle Korver         5.746479
                     ...    
Gary Neal           2.139000
DeJuan Blair        2.000000
Kelly Oubre Jr.     1.920240
Garrett Temple      1.100602
Jarell Eddie        0.561716
Name: 2015_SALARY, Length: 417, dtype: float64

### Digression: Series

- A *Series* is like an array, but with an index
- In particular, supports arithmetic

In [76]:
salaries_by_player.get("2015_SALARY")

PLAYER
Paul Millsap       18.671659
Al Horford         12.000000
Tiago Splitter      9.756250
Jeff Teague         8.000000
Kyle Korver         5.746479
                     ...    
Gary Neal           2.139000
DeJuan Blair        2.000000
Kelly Oubre Jr.     1.920240
Garrett Temple      1.100602
Jarell Eddie        0.561716
Name: 2015_SALARY, Length: 417, dtype: float64

In [77]:
# Step 2) Adjust the salaries for inflation
salaries_by_player.get("2015_SALARY") * 1.09

PLAYER
Paul Millsap       20.352108
Al Horford         13.080000
Tiago Splitter     10.634313
Jeff Teague         8.720000
Kyle Korver         6.263662
                     ...    
Gary Neal           2.331510
DeJuan Blair        2.180000
Kelly Oubre Jr.     2.093062
Garrett Temple      1.199656
Jarell Eddie        0.612270
Name: 2015_SALARY, Length: 417, dtype: float64

### Step 3) Add adjusted salaries to table

- Use `.assign(Name_of_column=data_in_array)` to assign an array (or series, or list) to a table.
- **Warning!** No quotes around `Name_of_column`
- Creates a new dataframe! Must save to variable.

In [78]:
salaries_by_player.assign(
    ADJUSTED_SALARY=salaries_by_player.get("2015_SALARY") * 1.09
)

POSITION                TEAM  2015_SALARY  ADJUSTED_SALARY
PLAYER                                                                    
Paul Millsap          PF       Atlanta Hawks    18.671659        20.352108
Al Horford             C       Atlanta Hawks    12.000000        13.080000
Tiago Splitter         C       Atlanta Hawks     9.756250        10.634313
Jeff Teague           PG       Atlanta Hawks     8.000000         8.720000
Kyle Korver           SG       Atlanta Hawks     5.746479         6.263662
...                  ...                 ...          ...              ...
Gary Neal             PG  Washington Wizards     2.139000         2.331510
DeJuan Blair           C  Washington Wizards     2.000000         2.180000
Kelly Oubre Jr.       SF  Washington Wizards     1.920240         2.093062
Garrett Temple        SG  Washington Wizards     1.100602         1.199656
Jarell Eddie          SG  Washington Wizards     0.561716         0.612270

[417 rows x 4 columns]

In [79]:
salaries_by_player

POSITION                TEAM  2015_SALARY
PLAYER                                                   
Paul Millsap          PF       Atlanta Hawks    18.671659
Al Horford             C       Atlanta Hawks    12.000000
Tiago Splitter         C       Atlanta Hawks     9.756250
Jeff Teague           PG       Atlanta Hawks     8.000000
Kyle Korver           SG       Atlanta Hawks     5.746479
...                  ...                 ...          ...
Gary Neal             PG  Washington Wizards     2.139000
DeJuan Blair           C  Washington Wizards     2.000000
Kelly Oubre Jr.       SF  Washington Wizards     1.920240
Garrett Temple        SG  Washington Wizards     1.100602
Jarell Eddie          SG  Washington Wizards     0.561716

[417 rows x 3 columns]

In [80]:
adjusted_salaries = salaries_by_player.assign(
    ADJUSTED_SALARY=salaries_by_player.get("2015_SALARY") * 1.09
)
adjusted_salaries

POSITION                TEAM  2015_SALARY  ADJUSTED_SALARY
PLAYER                                                                    
Paul Millsap          PF       Atlanta Hawks    18.671659        20.352108
Al Horford             C       Atlanta Hawks    12.000000        13.080000
Tiago Splitter         C       Atlanta Hawks     9.756250        10.634313
Jeff Teague           PG       Atlanta Hawks     8.000000         8.720000
Kyle Korver           SG       Atlanta Hawks     5.746479         6.263662
...                  ...                 ...          ...              ...
Gary Neal             PG  Washington Wizards     2.139000         2.331510
DeJuan Blair           C  Washington Wizards     2.000000         2.180000
Kelly Oubre Jr.       SF  Washington Wizards     1.920240         2.093062
Garrett Temple        SG  Washington Wizards     1.100602         1.199656
Jarell Eddie          SG  Washington Wizards     0.561716         0.612270

[417 rows x 4 columns]

## Use Case: Getting a particular player's salary

- How much did LeBron James make in 2015 (adjusted for inflation)?

In [81]:
# this is a Series!
adjusted_salaries.get('ADJUSTED_SALARY')

PLAYER
Paul Millsap       20.352108
Al Horford         13.080000
Tiago Splitter     10.634313
Jeff Teague         8.720000
Kyle Korver         6.263662
                     ...    
Gary Neal           2.331510
DeJuan Blair        2.180000
Kelly Oubre Jr.     2.093062
Garrett Temple      1.199656
Jarell Eddie        0.612270
Name: ADJUSTED_SALARY, Length: 417, dtype: float64

## Accessing a Series by row label: `.loc`

- Use `.loc[]` to *access* an element of the series with a particular row label

In [82]:
adjusted_salaries.get('ADJUSTED_SALARY').loc['LeBron James']

25.037845000000004

## How to get a particular element from a table:

1. `.get()` the column label
2. `.loc[]` the row label

In this class, we'll always get column, then row (but row, then column is also possible).

 Example: What position does LeBron play?

In [83]:
adjusted_salaries.get('POSITION').loc['LeBron James']

'SF'

## Use Case: Salary Analysis

- What was the biggest/smallest salary? What was the average salary?
- *Series* have helpful methods, like `.min()`, `.max()`, `.mean()`, etc.

In [84]:
adjusted_salaries.get('ADJUSTED_SALARY').min()

0.033667920000000004

In [85]:
adjusted_salaries.get('ADJUSTED_SALARY').max()

27.250000000000004

In [86]:
adjusted_salaries.get('ADJUSTED_SALARY').mean()

5.531547785395679

## Use Case: *Who* had the biggest salary?

- Strategy: Sort the table by salary and take the name at the top

### Step 1) Sort the table

- Use the `.sort_values(by=column_name)` method to sort.
- **Notice:** Creates a new table.
- Everything works as expected, but we wanted *descending* order.

In [87]:
adjusted_salaries.sort_values(by='ADJUSTED_SALARY')

POSITION                 TEAM  2015_SALARY  \
PLAYER                                                              
Thanasis Antetokounmpo       SF      New York Knicks     0.030888   
Cory Jefferson               PF         Phoenix Suns     0.049709   
Jordan McRae                 SG         Phoenix Suns     0.049709   
Orlando Johnson              SG         Phoenix Suns     0.055722   
Phil Pressey                 PG         Phoenix Suns     0.055722   
...                         ...                  ...          ...   
Dwight Howard                 C      Houston Rockets    22.359364   
Carmelo Anthony              SF      New York Knicks    22.875000   
LeBron James                 SF  Cleveland Cavaliers    22.970500   
Joe Johnson                  SF        Brooklyn Nets    24.894863   
Kobe Bryant                  SF   Los Angeles Lakers    25.000000   

                        ADJUSTED_SALARY  
PLAYER                                   
Thanasis Antetokounmpo         0.033668  
Cory Jefferson                 0.054183  
Jordan McRae                   0.054183  
Orlando Johnson                0.060737  
Phil Pressey                   0.060737  
...                                 ...  
Dwight Howard                 24.371707  
Carmelo Anthony               24.933750  
LeBron James                  25.037845  
Joe Johnson                   27.135401  
Kobe Bryant                   27.250000  

[417 rows x 4 columns]

### Step 1) Sorting the table in *descending* order

- Use `.sort_values(by=column_name, ascending=False)` to sort in *descending* order

In [88]:
highest_salaries = adjusted_salaries.sort_values(by='ADJUSTED_SALARY', ascending=False)
highest_salaries

POSITION                 TEAM  2015_SALARY  \
PLAYER                                                              
Kobe Bryant                  SF   Los Angeles Lakers    25.000000   
Joe Johnson                  SF        Brooklyn Nets    24.894863   
LeBron James                 SF  Cleveland Cavaliers    22.970500   
Carmelo Anthony              SF      New York Knicks    22.875000   
Dwight Howard                 C      Houston Rockets    22.359364   
...                         ...                  ...          ...   
Elliot Williams              SG    Memphis Grizzlies     0.055722   
Orlando Johnson              SG         Phoenix Suns     0.055722   
Cory Jefferson               PF         Phoenix Suns     0.049709   
Jordan McRae                 SG         Phoenix Suns     0.049709   
Thanasis Antetokounmpo       SF      New York Knicks     0.030888   

                        ADJUSTED_SALARY  
PLAYER                                   
Kobe Bryant                   27.250000  
Joe Johnson                   27.135401  
LeBron James                  25.037845  
Carmelo Anthony               24.933750  
Dwight Howard                 24.371707  
...                                 ...  
Elliot Williams                0.060737  
Orlando Johnson                0.060737  
Cory Jefferson                 0.054183  
Jordan McRae                   0.054183  
Thanasis Antetokounmpo         0.033668  

[417 rows x 4 columns]

### Step 2) Get the *name* of the person with the highest salary

- We saw that is was Kobe, but how do we get the name using code?
- Remember, the index is an array

In [89]:
highest_salaries.index[0]

'Kobe Bryant'

## Use Case: What team did the person with the third-lowest salary play for?

- We have the tools, but its a little tricky. Can you think of a strategy?

## Strategy #1

1. Sort the table in ascending order using `.sort_values(by='ADJUSTED_SALARY')`
2. Get the name of the person using `.index[2]` (remember starts at 0)
3. Use `.get('TEAM').loc[their_name]` to get their team name.



In [90]:
lowest_salaries = adjusted_salaries.sort_values(by='ADJUSTED_SALARY')
lowest_salaries

POSITION                 TEAM  2015_SALARY  \
PLAYER                                                              
Thanasis Antetokounmpo       SF      New York Knicks     0.030888   
Cory Jefferson               PF         Phoenix Suns     0.049709   
Jordan McRae                 SG         Phoenix Suns     0.049709   
Orlando Johnson              SG         Phoenix Suns     0.055722   
Phil Pressey                 PG         Phoenix Suns     0.055722   
...                         ...                  ...          ...   
Dwight Howard                 C      Houston Rockets    22.359364   
Carmelo Anthony              SF      New York Knicks    22.875000   
LeBron James                 SF  Cleveland Cavaliers    22.970500   
Joe Johnson                  SF        Brooklyn Nets    24.894863   
Kobe Bryant                  SF   Los Angeles Lakers    25.000000   

                        ADJUSTED_SALARY  
PLAYER                                   
Thanasis Antetokounmpo         0.033668  
Cory Jefferson                 0.054183  
Jordan McRae                   0.054183  
Orlando Johnson                0.060737  
Phil Pressey                   0.060737  
...                                 ...  
Dwight Howard                 24.371707  
Carmelo Anthony               24.933750  
LeBron James                  25.037845  
Joe Johnson                   27.135401  
Kobe Bryant                   27.250000  

[417 rows x 4 columns]

In [91]:
name = lowest_salaries.index[2]
name

'Jordan McRae'

In [92]:
lowest_salaries.get('TEAM').loc[name]

'Phoenix Suns'

## Another Approach

- To get the third element using `.loc[]`, we first had to find its label.
- Can we just get the 3rd element without knowing the label?
- Yes, with `.iloc[]`:

In [93]:
lowest_salaries.get('TEAM')

PLAYER
Thanasis Antetokounmpo        New York Knicks
Cory Jefferson                   Phoenix Suns
Jordan McRae                     Phoenix Suns
Orlando Johnson                  Phoenix Suns
Phil Pressey                     Phoenix Suns
                                 ...         
Dwight Howard                 Houston Rockets
Carmelo Anthony               New York Knicks
LeBron James              Cleveland Cavaliers
Joe Johnson                     Brooklyn Nets
Kobe Bryant                Los Angeles Lakers
Name: TEAM, Length: 417, dtype: object

In [94]:
lowest_salaries.get('TEAM').loc['Jordan McRae']

'Phoenix Suns'

In [95]:
lowest_salaries.get('TEAM').iloc[2]

'Phoenix Suns'

## Strategy #2

1. Sort the table in ascending order using `.sort_values(by='ADJUSTED_SALARY')`, as before.
2. Use `.get('TEAM').iloc[2]` to get their team name.

In [96]:
adjusted_salaries.sort_values(by='ADJUSTED_SALARY').get('TEAM').iloc[2]

'Phoenix Suns'

## Summary of accessing a Series

- There are two ways to get an element of a series:
    - `.loc[]` uses the row label
    - `.iloc[]` uses the integer position
- Usually `.loc` is more convenient

## Note

- Sometimes the integer position and row label are the same
- This happens by default with `bpd.read_csv`:

In [97]:
bpd.read_csv('data/nba_salaries.csv')

PLAYER POSITION                TEAM  2015_SALARY
0       Paul Millsap       PF       Atlanta Hawks    18.671659
1         Al Horford        C       Atlanta Hawks    12.000000
2     Tiago Splitter        C       Atlanta Hawks     9.756250
3        Jeff Teague       PG       Atlanta Hawks     8.000000
4        Kyle Korver       SG       Atlanta Hawks     5.746479
..               ...      ...                 ...          ...
412        Gary Neal       PG  Washington Wizards     2.139000
413     DeJuan Blair        C  Washington Wizards     2.000000
414  Kelly Oubre Jr.       SF  Washington Wizards     1.920240
415   Garrett Temple       SG  Washington Wizards     1.100602
416     Jarell Eddie       SG  Washington Wizards     0.561716

[417 rows x 4 columns]

In [98]:
bpd.read_csv('data/nba_salaries.csv').get('PLAYER').loc[3]

'Jeff Teague'

In [99]:
bpd.read_csv('data/nba_salaries.csv').get('PLAYER').iloc[3]

'Jeff Teague'

# More Questions

- What is the total payroll of the Cleveland Cavaliers?
- How many players make over 10 million?
- Who is the highest paid center (C)?